<?php

namespace CuisinonsBundle\Repository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByWeek()
    {
        $query = $this->createQueryBuilder('r')
            ->where('WEEK(r.date_at) = WEEK(NOW())')
            ->getQuery();

        return $query->getResult();
    }
}
