<?php

namespace Marmi\MarmiBundle\Repository;

/**
 * RecipeBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeBookRepository extends \Doctrine\ORM\EntityRepository
{
}
