<?php

namespace WCS\MarmiwildBundle\Repository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRecetteByNom($keyword)
    {
        $qb = $this->createQueryBuilder('r')
            ->where('r.nom like :keyword')
            ->setParameter('keyword', '%' . $keyword . '%');
        return $qb->getQuery()->getResult();
    }

    public function findRecetteByType($type)
    {
        $qb = $this->createQueryBuilder('r')
            ->where('r.type = :type')
            ->setParameter('type', $type);
        return $qb->getQuery()->getResult();
    }


    public function findRecetteByNbrePerson($nbrepersonne){

        $qb = $this->createQueryBuilder('r')
            ->where('r.personne = :nbrepersonne')
            ->setParameter('nbrepersonne', $nbrepersonne);
        return $qb->getQuery()->getResult();

    }
}