# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        CuisinonsBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
            ROLE_ADMIN:   ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: CuisinonsBundle:User
                property: username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            provider: our_db_provider
            form_login:
                login_path: cuisinons_login
                check_path: cuisinons_login
                default_target_path: cuisinons_homepage
                always_use_default_target_path: true
            logout:
                path:  /logout
                target: /login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
