marmiwild_homepage:
    path:     /
    defaults: { _controller: RecipesBundle:Default:index }

recipes_index:
    path:     /recipes
    defaults: { _controller: "RecipesBundle:Recipes:index" }
    methods:  GET

recipes_show:
    path:     /recipes/{id}/show
    defaults: { _controller: "RecipesBundle:Recipes:show" }
    methods:  GET

recipes_new:
    path:     /recipes/new
    defaults: { _controller: "RecipesBundle:Recipes:new" }
    methods:  [GET, POST]

recipes_edit:
    path:     /recipes/{id}/edit
    defaults: { _controller: "RecipesBundle:Recipes:edit" }
    methods:  [GET, POST]

recipes_delete:
    path:     /recipes/{id}/delete
    defaults: { _controller: "RecipesBundle:Recipes:delete" }
    methods:  DELETE
