<?php

namespace MarmiwildBundle\Repository;

/**
 * recetteIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class recetteIngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
