<?php

namespace Marmiwild\CoreBundle\Repository;

/**
 * Recette_IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Recette_IngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
