cuisinons_homepage:
    path:     /
    defaults: { _controller: CuisinonsBundle:Default:index }

cuisinons_login:
    path:     /login
    defaults: { _controller: CuisinonsBundle:Default:login }

cuisinons_logout:
    path:     /logout
    defaults: { _controller: CuisinonsBundle:Default:login }

cuisinons_recette_list:
    path:    /mes-recettes
    defaults: { _controller: CuisinonsBundle:Recette:list }

cuisinons_recette_add:
    path:    /nouvelle-recette
    defaults: { _controller: CuisinonsBundle:Recette:add }

cuisinons_recette_edit:
    path:    /edition-recette/{id}
    defaults: { _controller: CuisinonsBundle:Recette:edit }
    requirements:
        id: \d+

cuisinons_recette_delete:
    path:    /suppression-recette/{id}
    defaults: { _controller: CuisinonsBundle:Recette:delete }
    requirements:
        id: \d+

cuisinons_user_profil:
    path:    /profil-utilisateur/{id}
    defaults: { _controller: CuisinonsBundle:User:profil }
    requirements:
        id: \d+

cuisinons_user_register:
    path:    /inscription
    defaults: { _controller: CuisinonsBundle:User:register }